# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FitMi' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FitMi

  target 'FitMiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FitMiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
