# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'FitMi' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FitMi
  pod 'RealmSwift', '~> 2.0'
  pod 'FontBlaster'
  pod 'SwiftHTTP'
  pod 'BubbleTransition'
  pod 'JazzHands'
  pod 'Masonry'
  pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :branch => 'master'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'

  target 'FitMiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FitMiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['SWIFT_VERSION'] = '3.0'
		end
	end
end
