//
//  Constants.swift
//  FitMi
//
//  Created by Jinghan Wang on 3/10/16.
//  Copyright © 2016 FitMi. All rights reserved.
//

import Foundation

let APPLICATION_ERROR_DOMAIN = "com.fitmi.FitMi"
let ERROR_CODE_HEALTH_DATA_NOT_AVAILABLE = 2

let SPRITE_HEALTH_DEFAULT: Int = 100
let SPRITE_STRENGTH_DEFAULT: Int = 100
let SPRITE_STAMINA_DEFAULT: Int = 100
let SPRITE_AGILITY_DEFAULT: Int = 100

let SPRITE_HEALTH_WEIGHT_TODAY: Double = 0.05

let WORKOUT_GOAL_DEFAULT_STEPS: Int = 5000
let WORKOUT_GOAL_DEFAULT_DISTANCE: Int = 2500
let WORKOUT_GOAL_DEFAULT_FLIGHTS: Int = 5


let USER_DEFAULT_KEY_ONBOARD = "APP_ONBOARD_STATUS"
